<a href="https://colab.research.google.com/github/Santosh-Gupta/Lit2Vec2/blob/master/Lit2Vec2TrainingPublic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install LogUniform

In [0]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import re
from collections import Counter
import time

import loguniform
from loguniform import LogUniform

import numpy as np

from __future__ import print_function
import collections
import math
import numpy as np
import random
import zipfile
import os
import requests

from urllib.request import urlretrieve
from os.path import isfile, isdir
import zipfile
import tensorflow as tf
from matplotlib import pylab
from six.moves import range
from six.moves.urllib.request import urlretrieve
from sklearn.manifold import TSNE
import pandas as pd

from numpy import genfromtxt
import sys

numbBooks = 2829853+1 #according to https://github.com/zygmuntz/goodbooks-10k there are 10000 books in the dataset



In [0]:

def download_file_from_google_drive(id, destination):
    URL = "https://docs.google.com/uc?export=download"

    session = requests.Session()

    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)

    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)

    save_response_content(response, destination)    

def get_confirm_token(response):
    for key, value in response.cookies.items():
        if key.startswith('download_warning'):
            return value

    return None

def save_response_content(response, destination):
    CHUNK_SIZE = 32768

    with open(destination, "wb") as f:
        for chunk in response.iter_content(CHUNK_SIZE):
            if chunk: # filter out keep-alive new chunks
                f.write(chunk)
                

In [0]:
# download_file_from_google_drive('1w3uSNtc1srNaWoRHwbUE9o3baokloh9U', 'books.csv')

In [0]:
# dl_id = input("Enter Gdrive file ID for books: ") 

# dl_id =  '1w3uSNtc1srNaWoRHwbUE9o3baokloh9U'

# # DOWNLOAD ZIP
# print ("Downloading  file")
# myzip = drive.CreateFile({'id': dl_id})
# myzip.GetContentFile('books.csv')

# print( os.listdir() )


In [0]:
# b = pd.read_csv( 'books.csv' )
# b.head(30)
# bookDictionary = b.set_index('book_id').to_dict()['original_title']
# bookDictionary[5]

In [0]:
download_file_from_google_drive('1lH-0JqQ4UwgL-k83w9xrfftHzvx54phy', 'GoodReadsUser4MS.h5')

In [0]:
openHdf = pd.read_hdf('GoodReadsUser4MS.h5')

In [0]:
openHdf.loc[180:220]

UserID  EmbedID
180       1      180
181       1      181
182       1      182
183       1      183
184       1      184
185       1      185
186       1      186
187       1      187
188       1      188
189       1      189
190       1      190
191       1      191
192       1      192
193       1      193
194       1      194
195       1      195
196       1      196
197       1      197
198       1      198
199       1      199
200       2      102
201       2      200
202       2      201
203       2      202
204       2       92
205       2      203
206       2      204
207       2      205
208       2      113
209       2      206
210       2      207
211       2      208
212       2      209
213       2      210
214       2      211
215       2      212
216       2      147
217       2      192
218       2      213
219       2      214
220       2      215

In [0]:
my_data = openHdf.groupby('UserID')['EmbedID'].apply(list).values

In [0]:
my_data

array([list([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]),
       list([102, 200, 201, 202, 92, 203, 204, 205, 113, 206, 207, 208, 209, 210, 211, 212, 147

In [0]:
del openHdf

In [0]:
data_index = 0
epoch_index = 0
# recEpoch_indexA = 0 #Used to help keep store of the total number of epoches with the models

d1 = LogUniform(a=1, b=numbBooks)

def generate_batch(batch_size, posRate, negRate): 
  
    global data_index, epoch_index
    
    batch = np.zeros(shape=(batch_size, posRate), dtype=np.int32) 
    labels = np.zeros(shape=(batch_size, 1), dtype=np.int32)
    negs = np.zeros(shape=(batch_size, negRate), dtype=np.int32)

    n=0
    while n < batch_size:
        firstpick = np.random.choice( len(my_data[data_index]), 1)[0]
        labels[n] = my_data[data_index][firstpick]
        batchSet = my_data[data_index][:firstpick]+my_data[data_index][firstpick+1:]
        batch[n] = np.random.choice( batchSet , posRate)
        excludes = np.concatenate( (labels[n], batch[n]), axis=None)

        criterea0 = 0
        while criterea0 < negRate: #just in case 
            aa = d1.rvs(negRate*3).astype(int) 
            # aa = d1.rvs(negRate*4).astype(int) -1
            sampleCandidates = np.setdiff1d( aa, excludes )
            criterea0 = sampleCandidates.shape[0]

        negs[n] = np.random.choice( sampleCandidates, negRate, replace=False)

        n = n+1
        data_index = (data_index + 1) % len(my_data) #may have to do something like len my_data[:]
        if data_index == 0:
            epoch_index = epoch_index + 1
            print('Completed %d Epochs' % epoch_index)
    
    return batch, labels, negs    


In [0]:
here, goes, negs = generate_batch(20, 2, 3) 
print('batch', here)
print('labels', goes)
print('negs', negs)

batch [[107  57]
 [227 237]
 [238 250]
 [261 262]
 [311 358]
 [218 111]
 [473 473]
 [254 561]
 [587 568]
 [616 624]
 [648 657]
 [664 664]
 [714 216]
 [210 210]
 [746 758]
 [776 776]
 [887 844]
 [892 898]
 [930 930]
 [ 72 983]]
labels [[139]
 [192]
 [260]
 [124]
 [313]
 [455]
 [472]
 [544]
 [577]
 [611]
 [638]
 [661]
 [694]
 [736]
 [768]
 [777]
 [863]
 [902]
 [938]
 [978]]
negs [[   3734 2452227       4]
 [     54      36    1041]
 [    693   18915  448927]
 [  99931   56872      13]
 [  35808       1 1783325]
 [ 372779  237415   39032]
 [  45194     273   19165]
 [      9    1232  615156]
 [   2902    5316     286]
 [      9      27      37]
 [ 988960      74     313]
 [    375   12520  937319]
 [    245   80020      29]
 [      1      62       7]
 [ 326459     284  302935]
 [  93593 1465274       2]
 [     35     522      76]
 [ 604550 1619922    6501]
 [  30829  236680    1000]
 [   1995    1713    2529]]


In [0]:
class SkipGramModel(nn.Module):
    """Skip gram model of word2vec.
    Attributes:
        emb_size: Embedding size.
        emb_dimention: Embedding dimention, typically from 50 to 500.
        u_embedding: Embedding for center word.
        v_embedding: Embedding for neibor words.
    """

    def __init__(self, batchSize, skipWindow):
        """Initialize model parameters.
        Apply for two embedding layers.
        Initialize layer weight
        Args:
            emb_size: Embedding size.
            emb_dimention: Embedding dimention, typically from 50 to 500.
        Returns:
            None
        """
        super(SkipGramModel, self).__init__()
        self.emb_size = batchSize
        self.skipWindow = skipWindow
        self.emb_dimension = emb_dimension
        self.batchSize = batchSize
        self.u_embeddings = nn.Embedding(batchSize, emb_dimension, sparse=True).cuda()
        self.v_embeddings = nn.Embedding( batchSize, emb_dimension, sparse=True).cuda()
        # self.targets = torch.ones(34816).cud
        self.init_emb()

    def init_emb(self):
        """Initialize embedding weight like word2vec.
        The u_embedding is a uniform distribution in [-0.5/em_size, 0.5/emb_size], and the elements of v_embedding are zeroes.
        Returns:
            None
        """
        initrange = (2.0 / (numbBooks + self.emb_dimension)) ** 0.5 # Xavier init
        self.u_embeddings.weight.data.uniform_(-initrange, initrange)
        self.v_embeddings.weight.data.normal_(mean=0, std=math.sqrt(initrange))
        self.lossFunction = nn.BCEWithLogitsLoss( reduction = 'none' )

    def forward(self, pos_u, pos_v, neg_v, targets ):
        """Forward process.
        As pytorch designed, all variables must be batch format, so all input of this method is a list of word id.
        Args:
            pos_u: list of center word ids for positive word pairs.
            pos_v: list of neibor word ids for positive word pairs.
            neg_u: list of center word ids for negative word pairs.
            neg_v: list of neibor word ids for negative word pairs.
        Returns:
            Loss of this process, a pytorch variable.
        """
        emb_u = self.u_embeddings(pos_u)
        emb_v = self.v_embeddings(pos_v)
        neg_emb_v = self.v_embeddings(neg_v)

        scorePos = torch.bmm(emb_u, torch.transpose(emb_v, 1, 2)).squeeze()
        scoreNeg = torch.bmm( emb_u , torch.transpose(neg_emb_v, 1, 2) ).squeeze()

        #reduce to dot products for each set, and concatinate all the losses
        #noticed that the sign change for the negative sample dot products
        totalScores = torch.cat( ( scorePos.reshape(scorePos.shape[0], -1) , -scoreNeg.reshape(scoreNeg.shape[0], -1) ) , dim=1)

        indLoss = self.lossFunction( totalScores, targets )
        rowSum = torch.sum(indLoss, dim=1) #Sum all losses for each set
        finalLoss = torch.mean(rowSum) #Average losses across batches 

        return finalLoss

In [0]:
output_file_name = 'theOutpule.file'

emb_dimension = 400
batch_size = 128
posRate = 4
negRate = 128
iterationsMax = 40000 #200001
# initial_lr = 1.0

skip_gram_model = SkipGramModel(batch_size*(2*posRate+negRate), emb_dimension)
use_cuda = torch.cuda.is_available()
print('use cuda ? ', use_cuda)
if use_cuda:
    skip_gram_model.cuda()

optimizer = optim.Adagrad(
    skip_gram_model.parameters())

use cuda ?  True


In [0]:
import gc

In [0]:
gc.collect()

207

In [0]:
!pip install SpeedTorch

In [0]:
import SpeedTorch

In [0]:
uEmbed_switcher = SpeedTorch.ModelFactory( skip_gram_model.u_embeddings, total_classes=numbBooks, embed_dimension=400 )
vEmbed_switcher = SpeedTorch.ModelFactory( skip_gram_model.v_embeddings, total_classes=numbBooks, embed_dimension=400 )

In [0]:
initrange = (2.0 / (numbBooks + emb_dimension)) ** 0.5 # Xavier init
uEmbed_switcher.uniformDistributionInit( -initrange, initrange )
vEmbed_switcher.normalDistributionInit( 0, math.sqrt(initrange) )

In [0]:
uAdagrad_switcher = SpeedTorch.OptimizerFactory( optimizer, total_classes=numbBooks, embed_dimension=400, model=skip_gram_model, variable_name= 'u_embeddings', CPUPinn = True)
vAdagrad_switcher = SpeedTorch.OptimizerFactory( optimizer, total_classes=numbBooks, embed_dimension=400, model=skip_gram_model, variable_name='v_embeddings' , CPUPinn = True)

In [0]:
uAdagrad_switcher.optInit()
vAdagrad_switcher.optInit()

In [0]:
batch_size = 128
labelsDummyInput = uEmbed_switcher.variableTransformer( batchSize=batch_size, posPerBatch=1)
batchDummpyInput, negzDummyInput = vEmbed_switcher.variableTransformer( batchSize=batch_size, posPerBatch=4, negPerBatch=128 )

In [0]:
runningLoss = 0
runningStepTime = 0 
batch_size = 128
negSamp = 128
window_size = 2

targets = torch.ones( batch_size, window_size*2 + negSamp , dtype = torch.float32 ).cuda()

batchTensor = torch.from_numpy(batchDummpyInput)
LabelTensor = torch.from_numpy(labelsDummyInput)
negTensor = torch.from_numpy(negzDummyInput)

pos_u = Variable(torch.LongTensor(LabelTensor.long()))
pos_v = Variable(torch.LongTensor(batchTensor.long()))
neg_v = Variable(torch.LongTensor(negTensor.long()))

if use_cuda:
    pos_u = pos_u.cuda()
    pos_v = pos_v.cuda()
    neg_v = neg_v.cuda()

for i in range(80000):
    start = time.time()
    batch, labels, negz = generate_batch(batch_size=batch_size, posRate=4, negRate= 128)

    with torch.no_grad():
        uEmbed_switcher.beforeForwardPass( labels )
        vEmbed_switcher.beforeForwardPass( batch, negz )
        uAdagrad_switcher.beforeForwardPass( labels )
        vAdagrad_switcher.beforeForwardPass( batch, negz )

    optimizer.zero_grad()

    loss = skip_gram_model.forward(pos_u, pos_v, neg_v, targets)
    runningLoss = runningLoss + loss.data.item()

    loss.backward()
    optimizer.step()

    with torch.no_grad():
        uEmbed_switcher.afterOptimizerStep( labels )
        vEmbed_switcher.afterOptimizerStep( batch, negz )
        uAdagrad_switcher.afterOptimizerStep( labels )
        vAdagrad_switcher.afterOptimizerStep( batch, negz )

    end = time.time()
    runningStepTime = runningStepTime + end - start

    if i%100 == 0:
        print('i is ', i)
        print('loss is ', runningLoss/100)
        print('Average step time is ', runningStepTime/100)
        runningLoss = 0
        runningStepTime = 0





i is  52000
loss is  24.798086128234864
Average step time is  0.07182470083236694
i is  52100
loss is  24.741167640686037
Average step time is  0.07112337112426757
i is  52200
loss is  24.91937467575073
Average step time is  0.0710398030281067
i is  52300
loss is  24.830597553253174
Average step time is  0.07117151260375977
i is  52400
loss is  25.540252838134766
Average step time is  0.07145098447799683
i is  52500
loss is  24.378208885192873
Average step time is  0.07141171216964722
i is  52600
loss is  24.295829238891603
Average step time is  0.07101068258285523
i is  52700
loss is  24.338541355133056
Average step time is  0.07091912508010864
i is  52800
loss is  24.324116039276124
Average step time is  0.07124611377716064
i is  52900
loss is  24.288192501068114
Average step time is  0.07189893960952759
i is  53000
loss is  24.025996208190918
Average step time is  0.07162424802780151
i is  53100
loss is  24.23704013824463
Average step time is  0.07164643287658691
i is  53200
loss is

In [0]:
# i is  98500
# loss is  23.02226722717285
# Average step time is  0.07153946399688721
# Completed 18 Epochs
# i is  98600

In [0]:
del uAdagrad_switcher
del vAdagrad_switcher

In [0]:
del my_data

In [0]:
del vEmbed_switcher

In [0]:
gc.collect()

395

In [0]:
numpyU = uEmbed_switcher.getNumpyVersion()

In [0]:
numpyU

array([[-1.2862083e-01,  8.5094482e-02, -3.0265175e-02, ...,
        -8.2676597e-03, -2.9408952e-02,  1.8072788e-01],
       [ 2.3332495e-02,  3.0581463e-02, -3.4003556e-02, ...,
         2.9853960e-02,  3.2352291e-02, -1.8195402e-02],
       [ 1.2882236e-02,  1.4202858e-02, -1.3527294e-02, ...,
         1.4110753e-02,  1.3384230e-02, -1.0938700e-02],
       ...,
       [ 1.7646885e-04,  6.0551678e-04, -7.8915490e-04, ...,
         2.9078254e-04, -2.0462749e-04,  4.5109168e-04],
       [ 1.0356624e-02,  9.7975582e-03, -1.0615848e-02, ...,
         1.0558417e-02,  9.5852371e-03, -9.4440542e-03],
       [ 3.2403204e-05,  2.6075924e-05, -2.3735006e-04, ...,
        -1.0021922e-04,  7.6251494e-04,  1.8066516e-05]], dtype=float32)

In [0]:
numpyU.shape

In [0]:
# uEmbed_switcher.saveCupy( 'uEmbedsFinal.npy.cpy')
# # vEmbed_switcher.saveCupy( 'vEmbedsFinal.npy.cpy')

In [0]:
# np.save('testFile.npy',numpyU )

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
np.save('Lit2vec2p8Mil.npy', numpyU )

In [0]:
# num_points = 400

# tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000, method='exact')
# two_d_embeddings = tsne.fit_transform(final_embeddings[1:num_points+1, :])
# two_d_embeddingsSM = tsne.fit_transform(final_embeddingsSM[1:num_points+1, :])

In [0]:
# def plot(embeddings, labels):
#   assert embeddings.shape[0] >= len(labels), 'More labels than embeddings'
#   pylab.figure(figsize=(50,50))  # in inches
#   for i, label in enumerate(labels):
#     x, y = embeddings[i,:]
#     pylab.scatter(x, y)
#     pylab.annotate(label, xy=(x, y), xytext=(5, 2), textcoords='offset points',
#                    ha='right', va='bottom')
#   pylab.show()

# books = [bookDictionary[i] for i in range(1, num_points+1)]
# plot(two_d_embeddings, books)

In [0]:
# def plot(softmax_weightsPlot, labels):
#   assert softmax_weightsPlot.shape[0] >= len(labels), 'More labels than embeddings'
#   pylab.figure(figsize=(50,50))  # in inches
#   for i, label in enumerate(labels):
#     x, y = softmax_weightsPlot[i,:]
#     pylab.scatter(x, y)
#     pylab.annotate(label, xy=(x, y), xytext=(5, 2), textcoords='offset points',
#                    ha='right', va='bottom')
#   pylab.show()

# books = [bookDictionary[i] for i in range(1, num_points+1)]
# plot(two_d_embeddingsSM, books)